### ISSUE TITLE
Collapses the input

### ISSUE THREAD

**Issue by strarsis** [mynamesleon/input-autowidth#7]
@mynamesleon: When using this on an input field with spinner, the input field width collapses.

Having a library with known-working and browser-tested code for this task would be nice.

**Comment by mynamesleon** [comment]
Hi @strarsis. Could you please elaborate on this?

Are you emptying the input field, and then displaying a loading spinner next to it? The point of the library after all is to adjust the input width based on the string value inside.

The constructor can also take an options object, where you can specify a `minWidth` for the input, to prevent it from completely collapsing

**Comment by mynamesleon** [comment]
Closing this due to lack of reply from OP, and due to the library already catering for their issue,
